version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://tyotrack_user:Tyotrack@13!#@postgres:5432/tyotrack?schema=public
      - JWT_ACCESS_SECRET=tyotrack-dev-access-secret-key-32chars!
      - JWT_REFRESH_SECRET=tyotrack-dev-refresh-secret-key-32char!
      - JWT_ACCESS_EXPIRY=15m
      - JWT_REFRESH_EXPIRY=7d
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tyotrack-network

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tyotrack
      POSTGRES_USER: tyotrack_user
      POSTGRES_PASSWORD: Tyotrack@13!#
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tyotrack_user -d tyotrack" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tyotrack-network

volumes:
  postgres_data:


networks:
  tyotrack-network:
    driver: bridge
